/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:889909f5-809f-48f5-93de-6d7db602b363",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_vAIJLsoqM",
    "aws_user_pools_web_client_id": "1p105mlnkgqpp3uhjicrvbco9r",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://4t6qo6i2bbdihb2a3bbx3fdphy.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "Auth": {
        "Cognito": {
            "loginWith": {
                "oauth": {
                    "domain": "login.auth.ap-southeast-1.amazoncognito.com",
                    "scopes": [
                        "openid",
                        "profile",
                        "email",
                        "aws.cognito.signin.user.admin"
                    ],
                    "redirectSignIn": [
                        "http://localhost:5173/templates/pages/Homepage.html"
                    ],
                    "redirectSignOut": [
                        "http://localhost:5173/index.html"
                    ],
                    "responseType": "code"
                }
            }
        }
    }
};


export default awsmobile;
