name: Deploy to S3
on:
  push:
    branches:
      - main  # 或者你的主分支名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Configure AWS credentials BEFORE installing/running Amplify CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Should be ap-southeast-1

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Amplify Pull - Fetch backend config
        # Rely on credentials configured by the previous step
        run: amplify pull --appId du9jzij3tzrt5 --envName dev --yes

      - name: Build project with Vite
        run: npm run build

      # Credentials should persist from the earlier configure step
      # No need to reconfigure unless facing issues
      - name: Sync dist/ directory to S3 bucket
        run: |
          aws s3 sync ./dist s3://amplify-evydpddashboard-dev-f5d1e-deployment --delete --acl public-read
          # Note: --acl public-read makes objects publicly readable. This is okay for direct S3 hosting.
          # If you later add CloudFront with OAI/OAC, you might want to remove this flag
          # and make the bucket private again, relying on a bucket policy for CloudFront access.

      # Optional: Add step to invalidate CloudFront cache if using CloudFront
      # - name: Invalidate CloudFront Cache
      #   run: aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*" 