name: Deploy to S3
on:
  push:
    branches:
      - main  # 或者你的主分支名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      # Use AWS credentials for Amplify pull
      # Note: The credentials configuration might need to happen before Amplify CLI install depending on permissions,
      # but configuring it here ensures it's set before 'amplify pull'.
      - name: Configure AWS Credentials for Amplify
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Amplify Pull - Fetch backend config
        run: |
          amplify pull --appId du9jzij3tzrt5 --envName dev --yes
        env: # Pass credentials explicitly as env vars for Amplify CLI, just in case
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


      - name: Build project with Vite
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync dist/ directory to S3 bucket
        run: |
          aws s3 sync ./dist s3://amplify-evydpddashboard-dev-f5d1e-deployment --delete
          # Important: If using CloudFront, S3 objects should likely remain private.
          # If NOT using CloudFront and need public access, uncomment below:
          # aws s3 sync ./dist s3://amplify-evydpddashboard-dev-f5d1e-deployment --delete --acl public-read

      # Optional: Add step to invalidate CloudFront cache if using CloudFront
      # - name: Invalidate CloudFront Cache
      #   run: aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*" 